name: "Reusable Env Creation Workflow"

on:
  workflow_dispatch:
    inputs:
      envName:
        description: 'Type of environment to be created (dev, stg or prod)'
        required: true
        default: 'staging'

jobs:
  bicepCreateEnv:
    uses: ./.github/workflows/infracreation.yml
    with:
      envName: ${{ inputs.envName }}
      location: "centralIndia"
      subscriptionId: "8b256949-cf79-44b4-8c77-1c29b09ee5c2"
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      ubuntuAdminPassword: ${{ secrets.UBUNTU_ADMIN_PASSWORD }}
      ubuntuAdminUser: ${{ secrets.UBUNTU_ADMIN_USERNAME }}
